spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/fayerautos
spring.datasource.username=postgres
spring.datasource.password=senha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
