@startuml
skinparam packageStyle rectangle
left to right direction

actor "Visitante (Não Autenticado)" as Visitante
actor "Cliente" as Cliente
actor "Administrador" as Admin

rectangle FayerAutos {
    usecase "UC01 - Cadastrar Conta" as UC01
    usecase "UC02 - Efetuar Login" as UC02
    usecase "UC03 - Buscar Peças e Catálogo" as UC03
    usecase "UC04 - Gerenciar Carrinho de Compras" as UC04
    usecase "UC05 - Realizar Checkout (Finalizar Compra)" as UC05
    usecase "UC06 - Consultar Painel do Usuário" as UC06
    usecase "UC07 - Controlar Estoque e Peças" as UC07
}

Cliente --|> Visitante
Admin --|> Visitante

Visitante --> UC01
Visitante --> UC03
Visitante --> UC04

Cliente --> UC02
Cliente --> UC05
Cliente --> UC06

Admin --> UC02
Admin --> UC07

UC05 ..> UC02 : <<include>>
UC06 ..> UC02 : <<include>>
UC07 ..> UC02 : <<include>>

@enduml