spring.application.name=backend

spring.datasource.url=jdbc:postgresql://db.sajxqpcexotzocoivrgq.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=realchampsdata1!@#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true